DECLARE @columns NVARCHAR(MAX),
        @sql NVARCHAR(MAX);


WITH NAVTemp AS (
select 	t3.VALUEDATE,TRIM(t2.PORTFOLIOCODE) as PORTFOLIOCODE,t3.TOTALNAVAMOUNT AS TOTALNAVAMOUNT
		,ROUND(ROUND(t3.TOTALNAVAMOUNT / t1.AVAILUNIT,5), 4 ,1) AS NAVPerUnit
		
		,round(
			CAST(
				cast(t3.TOTALNAVAMOUNT as float) / cast( t1.AVAILUNIT as float)
				AS decimal(32,13))
			,12) AS NAVPerUnit_ProvidentFund
		, t1.AVAILUNIT
		,t3.TOTALAVAMOUNT as TOTALAVAMOUNT
		
		,ROUND(ROUND(t3.TOTALNAVAMOUNT / t1.AVAILUNIT,5), 4 ,1) AS NAVPerUnit_PropertyFund
		,round(
			CAST(
				cast(t3.TOTALNAVAMOUNT as float) / cast( t1.AVAILUNIT as float)
				AS decimal(32,13))
			,4) AS NAVPerUnit_PrivateFund
	FROM        INV_LHF.INVEST.HOLDINGUNIT AS t1 
	inner JOIN	INV_LHF.INVEST.PORTFOLIO AS t2 ON t1.PORTFOLIOID = t2.PORTFOLIOID and t2.ACTIVEFLAG = 'A'
	LEFT OUTER JOIN	INV_LHF.INVEST.TOTALNAV AS t3 ON t1.VALUEDATE = t3.VALUEDATE AND t1.PORTFOLIOID = t3.PORTFOLIOID
	WHERE     (t1.AVAILUNIT > 0) 
	and (t2.PORTFOLIOCODE like 'PF%')
	AND (t1.VALUEDATE between  '###AAA###' and '###BBB###') 
	GROUP BY t3.VALUEDATE,t2.PORTFOLIOCODE,t3.TOTALNAVAMOUNT, t3.TOTALAVAMOUNT , t1.AVAILUNIT 
	)

SELECT @columns = STUFF((
    SELECT DISTINCT ',' + QUOTENAME(PORTFOLIOCODE)
    FROM  NAVTemp
    --WHERE FundType = 'Mutual_Fund'
    FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)')
, 1, 1, '');


SET @sql = '

WITH NAVTemp AS (
select 	t3.VALUEDATE,TRIM(t2.PORTFOLIOCODE) as PORTFOLIOCODE,t3.TOTALNAVAMOUNT AS TOTALNAVAMOUNT
		,ROUND(ROUND(t3.TOTALNAVAMOUNT / t1.AVAILUNIT,5), 4 ,1) AS NAVPerUnit
		
		,round(
			CAST(
				cast(t3.TOTALNAVAMOUNT as float) / cast( t1.AVAILUNIT as float)
				AS decimal(32,13))
			,12) AS NAVPerUnit_ProvidentFund
		, t1.AVAILUNIT
		,t3.TOTALAVAMOUNT as TOTALAVAMOUNT
		
		,ROUND(ROUND(t3.TOTALNAVAMOUNT / t1.AVAILUNIT,5), 4 ,1) AS NAVPerUnit_PropertyFund
		,round(
			CAST(
				cast(t3.TOTALNAVAMOUNT as float) / cast( t1.AVAILUNIT as float)
				AS decimal(32,13))
			,4) AS NAVPerUnit_PrivateFund
	FROM        INV_LHF.INVEST.HOLDINGUNIT AS t1 
	inner JOIN	INV_LHF.INVEST.PORTFOLIO AS t2 ON t1.PORTFOLIOID = t2.PORTFOLIOID and t2.ACTIVEFLAG = ''A''
	LEFT OUTER JOIN	INV_LHF.INVEST.TOTALNAV AS t3 ON t1.VALUEDATE = t3.VALUEDATE AND t1.PORTFOLIOID = t3.PORTFOLIOID
	WHERE     (t1.AVAILUNIT > 0) 
	--and (t2.PORTFOLIOCODE in ())
	AND (t1.VALUEDATE between  ''###AAA###'' and ''###BBB###'') 
	GROUP BY t3.VALUEDATE,t2.PORTFOLIOCODE,t3.TOTALNAVAMOUNT, t3.TOTALAVAMOUNT , t1.AVAILUNIT 
	)


	select VALUEDATE , ' + @columns + ' from 
	(
		SELECT VALUEDATE , TOTALNAVAMOUNT , PORTFOLIOCODE
		FROM  NAVTemp
		WHERE VALUEDATE BETWEEN ''###AAA###'' AND ''###BBB###''
	) AS SourceTable
	PIVOT (
		SUM(TOTALNAVAMOUNT)
		FOR PORTFOLIOCODE IN (' + @columns + ')
	) AS PivotTable
	ORDER BY VALUEDATE;';


	
EXEC sp_executesql @sql;
	
