SELECT  DATEADD(day, -1, CAST(GETDATE() AS DATE)) as Date 
,SECURITYCODE
,PORTFOLIOID
,PORTFOLIOCODE
,SECTORCODE
,ISSUERCODE
,BUYUNIT
,BUYNETAMOUNT
,SELLUNIT
,SELLNETAMOUNT
,(BUYUNIT - SELLUNIT) as Total_unit_Amount
,LASTTRADEDATE
,PRICECODE
,BASECURRENCY
,BOOKVALUEPERUNIT
,ACTION
,EXCHANGERATE
,MARKETUNITCOST
,BUYLOCALAMOUNT
,MARKETUNITCOST
,BUYLOCALAMOUNT as Total_Cost_THB
,MARKETUNITCOST * BUYUNIT * EXCHANGERATE as Market_Price_Amount
,(MARKETUNITCOST * BUYUNIT * EXCHANGERATE) - BUYLOCALAMOUNT  as Profit_Loss

  FROM [INV_LHF].[INVEST].[HOLDING]
  where SECURITYCODE = 'wash'
 -- where PORTFOLIOCODE = 'PFI0190'