SELECT  DATEADD(day, -1, CAST(GETDATE() AS DATE)) as Date 
,SECURITYCODE
,PORTFOLIOID
,PORTFOLIOCODE
,SECTORCODE
,ISSUERCODE
,BUYUNIT
,BUYNETAMOUNT
,SELLUNIT
,SELLNETAMOUNT
,(BUYUNIT - SELLUNIT) as Total_unit_Amount
,LASTTRADEDATE
,PRICECODE
,BASECURRENCY
,BOOKVALUEPERUNIT
,ACTION
,EXCHANGERATE
,MARKETUNITCOST
,BUYLOCALAMOUNT
,MARKETUNITCOST * (BUYUNIT - SELLUNIT) as Total_Cost_THB
,MARKETUNITCOST * (BUYUNIT - SELLUNIT) * EXCHANGERATE as Market_Price_Amount
,(MARKETUNITCOST * (BUYUNIT - SELLUNIT) * EXCHANGERATE) - BUYLOCALAMOUNT  as Profit_Loss
,(NULLIF((MARKETUNITCOST * (BUYUNIT - SELLUNIT) * EXCHANGERATE),0) /NULLIF(BOOKVALUEPERUNIT * (BUYUNIT - SELLUNIT) *EXCHANGERATE,0)*100.0)-100  as Percent_Profit_Loss

  FROM [INV_LHF].[INVEST].[HOLDING]
  where PRICECODE != ''
 -- where SECURITYCODE = 'wash'
 -- where PORTFOLIOCODE = 'PFI0190'

 order by  Percent_Profit_Loss desc


